"""add role and 2fa fields

Revision ID: 681f9c4a7fb4
Revises: 001_add_user_roles
Create Date: 2026-05-08 02:09:09.823827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '681f9c4a7fb4'
down_revision: Union[str, None] = '001_add_user_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create enum type first (already exists due to partial run)
    userrole_enum = sa.Enum('user', 'admin', name='userrole')
    # userrole_enum.create(op.get_bind())
    
    # Drop default before altering type to avoid cast error
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=userrole_enum,
               postgresql_using='role::userrole',
               existing_nullable=False,
               server_default=sa.text("'user'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='userrole'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
